server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /

chatgpt:
  token: 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
  proxy-host: 127.0.0.1
  proxy-port: 7890
  session-expiration-time: 30
